README.md

* Added a note about where to find Guild and Channel IDs for the `.env` file.
* Added commands to run the bot using [screen](https://www.gnu.org/software/screen/manual/screen.html) so the bot continues to run after disconnecting the SSH session

Add additional running commands to README

---

.github/workflows/docker_upload.yml

- Upload latest + git commit has on ever push to main
- Upload latest_relesae when we do a github release
Need secrets added and potentially change of the Docker Hub image name etc.
Fixes #24

Add Docker Action

---

README.md

I installed your project and played with it a bit. Seems to be working pretty good! I will familiarize myself with the code some more and perhaps offer some help coding if you're interested.

Did some formatting on the readme file and added missing lines in .env example

---

.gitignore
cogs/draw_image_generation.py
cogs/gpt_3_commands_and_converser.py
cogs/image_prompt_optimizer.py
gpt3discord.py
models/check_model.py

Add gitignore and change role checks

---

cogs/draw_image_generation.py
cogs/gpt_3_commands_and_converser.py

Views failed to remove or edit, happened to see it in the log after an hour passed

Fix view message edits

---

README.md
cogs/gpt_3_commands_and_converser.py

What's your thoughts on changing `end-chat` to `end`?

Implement /gpt end

---

cogs/draw_image_generation.py
cogs/image_prompt_optimizer.py
models/openai_model.py

Since boosted servers have higher limits, even for bots

Changed the image resizing to go by the guild filesize limit

---

README.md

Added a section on how to update the bot

Added a section on how to update the bot 

---

.gitignore
cogs/gpt_3_commands_and_converser.py
cogs/image_prompt_optimizer.py

Check if I've missed any spots and check reliability
resolves #83

Replace mention with server nickname

---

README.md
cogs/draw_image_generation.py
cogs/gpt_3_commands_and_converser.py
cogs/image_prompt_optimizer.py
models/openai_model.py
models/user_model.py

Added codex to the edit command too
Fixed up the readme a bit
Added support for a persistent model specific to a thread, haven't added any way to set it currently, should have some lookup of the max tokens of each model

Add the edit endpoint

---

README.md
cogs/commands.py
cogs/moderations_service_cog.py
cogs/text_service_cog.py
gpt3discord.py
services/moderations_service.py

- `/mod config`
- Save thresholds to SQLite and parameterize the moderations service

parameterize moderations thresholds for warns and deletes

---

README.md
cogs/commands.py
cogs/image_service_cog.py
cogs/moderations_service_cog.py
cogs/text_service_cog.py
gpt3discord.py
services/image_service.py
services/text_service.py

Add context menu buttons
https://i.imgur.com/fkfnJQ0.png

context menu buttons

---

cogs/commands.py
cogs/image_service_cog.py
cogs/moderations_service_cog.py
cogs/prompt_optimizer_cog.py
cogs/text_service_cog.py
gpt3discord.py
models/autocomplete_model.py
models/check_model.py
models/openai_model.py
models/user_model.py
services/deletion_service.py
services/environment_service.py
services/image_service.py
services/message_queue_service.py
services/moderations_service.py
services/pinecone_service.py
services/text_service.py
services/usage_service.py

Got a bit to lazy to add more docstrings but the cogs mostly have some basic ones
Check if I introduced any new bugs with the bugfixes lol

Added some docstrings, some bugfixes and general cleaning

---

models/autocomplete_model.py
models/openai_model.py
services/moderations_service.py

- Removes magic values, making it configuarable from one place and requiring less code changes in the future
- Updates auto-complete to fetch the configuration values instead
- Adds the missing models
- Fixes the values assigned to top_p and temperature under different modes

Add missing models / Code cleanup

---

models/user_model.py
services/text_service.py

Fix spelling mistakes

---

detailed_guides/How to host on Azure app service.md

Signed-off-by: falkoro <39274208+falkoro@users.noreply.github.com>

Create How to host on Azure app service.md

---

Dockerfile
README.md
cogs/commands.py
cogs/index_service_cog.py
models/autocomplete_model.py
models/index_model.py
requirements.txt
services/usage_service.py

Fix regression in full discord server indexing
Add back response mode, only on vector index queries
Added the llmpredictor to queries
Fix docker build
Update requirements

Various gpt-index fixes

---

cogs/text_service_cog.py
services/text_service.py

Fix conversation limit thread closing logic for other users
Return early on conversation processing if the conversation limit is reached

Fix some conversation logic regressions

---

pyproject.toml
requirements.txt
requirements_base.txt

Revert "Bump py-cord from 2.3.2 to 2.4.0"

---

.github/workflows/build-and-publish-docker.yml
docker-compose.yml
models/index_model.py
models/openai_model.py
models/search_model.py
services/environment_service.py

Add a `save_path()` function to the EnvService which is the `SHARE_DIR` if set, if not it's the `app_root_path()`
Also clarifying that `find_shared_file()` returns the first valid path. If the path exists in the `SHARE_DIR` folder, it won't also load the files from the `app_root_path()` dir. But if it doesn't exist in `SHARE_DIR` but does exist in `app_root_path()` it will load that
Fix ghcr.io having double base and full to the image name
Add some comments to the compose file

Docker persistence fixes and other fixes

---

pyproject.toml
requirements.txt
requirements_base.txt
requirements_full.txt

Move tqdm from optional to required
Add tqdm to requirements.txt
#214

Possibly fix some tqdm requirements issues

---

detailed_guides/AI-SEARCH.md
detailed_guides/TRANSLATIONS.md

Improved the docs for obtaining API keys & IDs with step by step instructions & images

Improve docs with images

---

sample.env

Refactored .env file and reorganized variables for cleanliness.

Raecaug env refactor

---

detailed_guides/MULTI-MODALITY.md
sample.env

Fixed typo of variable name in documentation.
Added Replicate and Google Cloud env variables for new multi-modal functions.

Typo fix & env bump

---

cogs/index_service_cog.py
detailed_guides/CUSTOM-INDEXES.md
sample.env
services/environment_service.py

Should take care of #282. Added variable to env and a note of it in the index docs.

GitHub token bump

---

detailed_guides/AI-SEARCH.md
detailed_guides/DROPLET-GUIDE.md
detailed_guides/INSTALLATION.md

- Link to droplet guide in repo instead
- Add Kaveen's referral link to droplet guide
- Add cloud vision API to Google section
- Include GUI of connecting to server in addition to ssh
- Include urlib3 installation required for DigitalOcean

Update installation instructions

---

README.md

Removed "(You can try out the bot here also in a limited fashion)" from the support server link.

Update README.md to not include trying out bot

---

image_optimizer_pretext.txt

acrylyc -> acrylic
seperated -> separated

Fixed typo error in image_optimizer_pretext.txt

---

sample.env

Add E2B enviroment variable to sample.env and fix formatting bugs.

Add E2B env variable

---

cogs/code_interpreter_service_cog.py
cogs/image_service_cog.py
cogs/search_service_cog.py
cogs/text_service_cog.py
models/index_model.py
utils/safe_ctx_respond.py

add utility function to safely respond to Discord interactions

---

cogs/code_interpreter_service_cog.py
cogs/image_service_cog.py
cogs/search_service_cog.py
cogs/text_service_cog.py
models/index_model.py
utils/__init__.py
utils/safe_ctx_respond.py

#368 
Actually, the error in my code was of some type annotation stuff I tried to do, wich was *obviously* wrong, but it got in the commit for some reason. Here is the code, fixed. I tested it with code chat & gpt chat, and it works.

Fix for Unknown Interaction errors

---

gpt3discord.py
models/openai_model.py

https://github.com/Kav-K/GPTDiscord/issues/410

fixed gpt3.5 ask bug and bumped version
