- Dockerfile
- README.md
- cogs/gpt_3_commands_and_converser.py
- cogs/image_prompt_optimizer.py
- main.py
- models/usage_service_model.py
- Add a Dockerfile so people can run this bot in a docker container
- Stuck with recommendation of running with python3.9 for now
- Will later test with 3.11 + supply fixes if I get this working ...
- Added a DATA_DIR env param to use to choose the directory to write data we want persistent across docker container restarts to be written to
- We default to CWD like the code does today - we just explicitly pass it to functions / classes
Test:
- `docker build -t gpt3discord .`
```
crl-m1:GPT3Discord cooper$ docker image ls
REPOSITORY                     TAG               IMAGE ID       CREATED          SIZE
gpt3discord                    latest            6d2832af2450   69 seconds ago   356MB
```
- `docker run --name gpt3discord -v ~/gpt3discord/env:/bin/.env -v ~/gpt3discord/data:/data …
> Add Dockerfile + concept of a DATA_DIR

- .github/workflows/build.yml
- Dockerfile
- README.md
- gpt3discord.py
- pyproject.toml
- requirements.txt
- Add a pyproject.toml to install all modules and packages
- Use hatch to build + install
- Still only claim support for 3.9
- We don't specify versions in pyproject.toml on purpose so people can have some flexibility there
- If they want the tested pinned versions they can use requirements.txt like Docker + CI does ...
- This will allow the package to be uploaded to PyPI if you'd like now :)
- `git mv main.py gpt3discord.py` as main.py is to common (incase someone installs to shared python env)
- Move initalization code into a init() function to have entry point script call
- Update `Dockerfile` to install via pyproject.toml
- Both docker + build CI install requirements.txt so we get the known versions of dependencies that work
- Update README for less steps now in installing
- Side …
> Add pyproject.toml for building / installing

- .github/workflows/pypi_upload.yml
- Add a GitHub action to publish a source distribution (sdist) + wheel (binary package) to PyPI
- PyPI will create the package on upload unlike Docker Hub
This will need a PYPI_TOKEN secret added. Please go register @ pypi.org make a token please + add to GitHub secrets
- Later on you could swap the token locked to this one module if you want to be security concious
- (Please do this before merging)
Fixes #25
> Add PyPI Uploading

- Dockerfile
- We were not putting the modules in a dir so it was not being included in the install
- Fix the COPY directives
- Add a `find` run to show the src layout so someone building / looking at logs can inspect easy
Ran and got a new error which I will open an issue for using your recent additons ...
> Fix COPY of cogs + models source code into build Docker container

- cogs/gpt_3_commands_and_converser.py
- conversation_starter_pretext_minimal.txt
Here's a working private thread with an opener. Also added a minified starter with less personality traits while still containing the formatting cues.
There's currently only one bug that I'm aware of, when using the opener, the opener message which is replied to with the generation has a non-working end conversation button, redo works. The "end" sentences also works. After sending the first user message after the generation the end button works as normal.
Might be other bugs I haven't caught on, or possible improvements
resolves #30 resolves #33
> Add private threads, minified starter and added option for opening/preamble

- cogs/gpt_3_commands_and_converser.py
Replace 'Human:' in prompt with actual username. 
- makes for more natural summaries
- makes for more natural conversation
- encourages bot to act as one person to another, instead of as bot to a human.
> Replace 'Human:' in prompt with actual username

- README.md
- cogs/gpt_3_commands_and_converser.py
- models/openai_model.py
Added optional `temperature`, `top_p`, `frequency_penalty` and `presence_penalty` to the `/gpt ask` command, you can chose to only include one, or include all of them. Checked the output of the `payload` to see if they passed properly, didn't on `0` so I had to change how the overrides are checked for in the `payload`.
> Added passthrough of gpt3 parameters to /ask

- cogs/gpt_3_commands_and_converser.py
- conversation_starter_pretext.txt
- conversation_starter_pretext_minimal.txt
- models/openai_model.py
- models/user_model.py
The one starting the thread is marked as thread owner
You can only own one thread but can converse in multiple threads, to keep spam down and keep things simple
The thread owner is the only one who can end the conversation, for redoing messages only the one who sent the original message can change it.
Added a check `discord.DMChannel` for the message edit moderation 
Gave an error when opening a conversation and then ending it due to the ephemeral message
Changed `Human` to `<username>` in prompts  and inserted as `'username' : ` for the conversation itself. Will have to see if it's better to remove the <> at some point
Functions that added `Human` now directly adds the discord user name. Will have to see if it's necessary to add any checks to it
Do you think we should set the username or …
> Changed conversations to be keyed by thread allowing multi user conversations

- README.md
- cogs/gpt_3_commands_and_converser.py
- gpt3discord.py
- models/user_model.py
- openers/english_translator.json
Added the ability to load .json files which include temp, top p, frequency and presence penalties. Also fixed some path traversal possibilities with opener files. Reordered the parts of `/gpt converse` some too. A review and sanity check that the path traversal isn't possible anymore would be appreciated
In reference to discussion started by @uberdude420
> Add parameter overrides to opener files using json

- README.md
- cogs/gpt_3_commands_and_converser.py
- models/env_service_model.py
- sample.env
This pull request adds the ability to configure the path of the SQLite database file, allowing for greater flexibility in managing database storage. 
- Added a new configuration option for specifying the path of the SQLite database file
- Updated the code to properly handle the new configuration option
- Tested the changes
- Run the application with the new configuration option for the path of the SQLite database file
- Verify that the database file is created in the specified path
N/A
This pull request closes https://github.com/Kav-K/GPT3Discord/issues/99
Signed-off-by: Alessandro Bellia <casildaserrano@yahoo.it>
> Added the possibility to configure SQLITE db path

- README.md
- cogs/text_service_cog.py
- gpt3discord.py
- services/environment_service.py
- services/moderations_service.py
- services/text_service.py
Adds a check for CHAT_BYPASS_ROLES in the environment file to allow specific roles to bypass the automoderation service when enabled.
> Add support for CHAT_BYPASS_ROLES in Env

- gpt3discord.py
- Docker sends SIGTERM on `docker restart` and `docker stop`
- We need to cleanup the PID_FILE when this occurs so that when the container starts again the PID_FILE is not there
- Move logic to a function to KeyboardInterupt / SIGINT exit flow uses same cleanup as SIGTERM
- I also added a function to check in Linux only that if the PID stored isn't actually running we'll remove the file and allow gpt3discord to start
Test:
- Build a docker container and run + restart locally
- `docker build -t gpt3discord .`
- `docker run --name gpt3discord -v /containers/gpt3discord/env:/opt/gpt3discord/etc/environment -v /containers/gpt3discord/data:/data gpt3discord:latest`
- `docker restart gpt3discord`
See logs do what we need:
```
Commands synced
Killed all subprocesses
Removing PID file bot.pid …
```
> Handle SIGTERM exits Cleanly too

- cogs/commands.py
- cogs/text_service_cog.py
- conversation_starter_pretext.txt
- conversation_starter_pretext_minimal.txt
- gpt3discord.py
- image_optimizer_pretext.txt
- models/openai_model.py
- services/text_service.py
Also fixes an error message on the redo view timeout on a closed thread
Had to use the .text because the timestamp of the original prompt is not the same as the timestamp of the redo prompt
Removed fetch_message, can't see any bugs from removing it. Will allow the usage of ephemeral defers that use encapsulate_send
> Fix conversation redos

- cogs/commands.py
- cogs/text_service_cog.py
- gpt3discord.py
- models/autocomplete_model.py
- models/openai_model.py
Added option to set a model when opening a conversation thread, currently taken from `TEXT_MODELS`
Changed the backoff handler to use the `ValueError` where `valid_text_request` is used due to providing a more verbose error to the user
Reduced max tokens set if model can't be found in the list from 4024 to 2024, less prone to api errors 
Added ephemeral options to ask and edit
closes #125 I believe, should be able to type in the finetuned models name into the option when starting a conversation, or add it to the code to get it from the list. I haven't been able to test this since I don't have a finetuned model readily available
> Add the ability to set model in threads

- .github/dependabot.yml
Let's have automation tell us when there are new action versions.
- It can also do pip - but we can add that in a seperate PR if there is interest ...
Right now we will get PRs once a week if there are new versions.
Test:
- Load with pyyaml to ensure valid yaml
> Add dependabot to update GitHub actions

- .github/dependabot.yml
- Once a week dependabot will look at dependencies and open a PR per depdency as they upgrade
- This will ensure we don't get to far behind without knowing a reason (hopefully via CI) not to upgrade
> Add pip (requirements) dependabot updating

- cogs/text_service_cog.py
- services/text_service.py
I believe this fixes #203
I have not added the conversation view though possible, because the redo function doesn't account for what it's redoing being split into multiple messages. Can use pagination but it doesn't look nice in a conversation imo. Thoughts on doing it that way?
> Fix split messages in conversations breaking conversation

- .github/workflows/build-and-publish-docker.yml
Build amd64 and arm64 images together on pr, can be separated into an extra action if required.
> Add arm64 to pr build

- .github/workflows/build.yml
- Dockerfile
- Build via Python 3.10 in Docker
- I originally tried python3.11 as there are lots of perf wins there but we have build errors I don't want to debug at this time
- Add CI to build with python3.10 on CI too
Test:
- Build it - `docker build --build-arg FULL=true -t gpt3discord .`
```
crl-m1:GPT3Discord cooper$ docker image ls
REPOSITORY                     TAG               IMAGE ID       CREATED          SIZE
gpt3discord                    latest            6cd5ff57745d   14 seconds ago   1.14GB
```
- This is an aarch64 build too
```
Darwin crl-m1.cooperlees.com 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64
```
> Build Docker image with 3.10

- .github/workflows/build-and-publish-docker.yml
- .gitignore
- Dockerfile
- gpt3discord.py
https://github.com/rust-lang/cargo/issues/10583
Removed extra swap as it's not needed anymore
> Add patch for cargo mem leak on aarch64

- models/embed_statics_model.py
Better looking static embed thumbnail icons. Includes updates to the checkmark and crossmark.
Examples:
Updated:
Previous:
> Better Embed Images

- cogs/commands.py
- cogs/text_service_cog.py
- gpt3discord.py
- models/index_model.py
- models/search_model.py
- pyproject.toml
- requirements.txt
- requirements_base.txt
- services/usage_service.py
> Fix indexing and search

- README.md
- cogs/commands.py
- cogs/search_service_cog.py
- cogs/transcription_service_cog.py
- models/autocomplete_model.py
- models/check_model.py
- models/index_model.py
- models/openai_model.py
- models/search_model.py
- pyproject.toml
- requirements.txt
- requirements_base.txt
- requirements_full.txt
- services/text_service.py
- services/usage_service.py
Fixes #316 #312 
- Fix a recurring error message related to KeyError due to the user being in redo_users but doesn't have an original_message entry.
- Enable the usage of the newly updated models. More turbo and gpt4 models to pick from for index and search. Set default model if the one in the db is not in TEXT_MODELS on restart. Refactored the usage service. Removed babbage and ada.
- Add support for shortened youtube links. Replaced pytube with yt-dpl for transcription. Added youtube link validation and redirect check. Removed await on .read() in openai_model as those functions aren't async.
- Move the nltk dependency in the requirements files.
- Fix the web crawling part of the internet chat. Made the limit dynamic based on model for when to index the website.
- Switch to counting …
> Enable new models, fix internet chat, fix youtube transcription, bugfixes and other small changes

- pyproject.toml
- requirements.txt
- requirements_base.txt
Removed PyPDF2, deprecated
Fixes #332
> Add pypdf dependency

- Dockerfile
Fixes the following error when running from Docker:
```
File "/opt/gpt3discord/bin/gpt3discord.py", line 14, in <module>
from cogs.code_interpreter_service_cog import CodeInterpreterService
File "/usr/local/lib/python3.10/site-packages/cogs/code_interpreter_service_cog.py", line 38, in <module>
from utils.safe_ctx_respond import safe_ctx_respond, safe_remove_list
ModuleNotFoundError: No module named 'utils'
```
> Fix missing utils when running via Docker

- detailed_guides/INSTALLATION.md
Fix beta.openai.com to be platform.openai.com
> Fix openai api Key url

- README.md
- detailed_guides/AI-MODERATION.md
- detailed_guides/AI-SEARCH.md
- detailed_guides/CODE-INTERPRETER.md
- detailed_guides/INSTALLATION.md
- detailed_guides/INTERNET-CONNECTED-CHAT.md
- sample.env
Updated several guides with additional screenshots, useful tertiary information and small fixes to errors or typos.
> Documentation refresh
